import { describe, expect, it } from "vitest";
import { ClaudeEmitter } from "../src/emitters/claude.js";
import type { CommandSpec, RulesContext } from "../src/core/types.js";

const spec: CommandSpec = {
  id: "specify",
  name: "amby.specify",
  description: "Turn a feature idea into a spec.",
  argumentHint: "<feature description>",
  phase: "specify",
  reads: [],
  writes: [],
  allowedTools: ["read", "write", "edit"],
  body: "Write a specification.",
};

function ctx(manageRules: boolean): RulesContext {
  return { projectName: "demo", specs: [spec], manageRules };
}

describe("ClaudeEmitter", () => {
  it("emits one command file at the expected path (FR-001)", () => {
    const files = new ClaudeEmitter().emit([spec], ctx(false));
    expect(files).toHaveLength(1);
    expect(files[0]!.path).toBe(".claude/commands/amby.specify.md");
    expect(files[0]!.scope).toBe("project");
  });

  it("maps abstract tools to Claude names (FR-002)", () => {
    const file = new ClaudeEmitter().emit([spec], ctx(false))[0]!;
    expect(file.contents).toContain("allowed-tools: Read, Write, Edit");
  });

  it("quotes non-YAML-safe frontmatter values (FR-003)", () => {
    const file = new ClaudeEmitter().emit([spec], ctx(false))[0]!;
    expect(file.contents).toContain('argument-hint: "<feature description>"');
    expect(file.contents).toContain('description: "Turn a feature idea into a spec."');
  });

  it("includes the generated notice and the verbatim body", () => {
    const file = new ClaudeEmitter().emit([spec], ctx(false))[0]!;
    expect(file.contents).toContain("GENERATED by AmbyKit from src/prompts/specify.md");
    expect(file.contents.trimEnd().endsWith("Write a specification.")).toBe(true);
  });

  it("adds a CLAUDE.md bridge only when rules are managed", () => {
    const withRules = new ClaudeEmitter().emit([spec], ctx(true));
    const bridge = withRules.find((f) => f.path === "CLAUDE.md");
    expect(bridge).toBeDefined();
    expect(bridge!.contents.startsWith("@AGENTS.md")).toBe(true);

    const withoutRules = new ClaudeEmitter().emit([spec], ctx(false));
    expect(withoutRules.find((f) => f.path === "CLAUDE.md")).toBeUndefined();
  });
});
