import { describe, expect, it } from "vitest";
import { OpenCodeEmitter } from "../src/emitters/opencode.js";
import { CursorEmitter } from "../src/emitters/cursor.js";
import { CursorCliEmitter } from "../src/emitters/cursor-cli.js";
import { AntigravityEmitter } from "../src/emitters/antigravity.js";
import { AntigravityCliEmitter } from "../src/emitters/antigravity-cli.js";
import type { CommandSpec, RulesContext } from "../src/core/types.js";

const spec: CommandSpec = {
  id: "specify",
  name: "amby.specify",
  description: "Turn a feature idea into a spec.",
  argumentHint: "<feature description>",
  phase: "specify",
  reads: [],
  writes: [],
  allowedTools: ["read", "write", "edit"],
  body: "Write a specification for: **$ARGUMENTS**",
};

const ctx = (manageRules: boolean): RulesContext => ({ projectName: "demo", specs: [spec], manageRules });

describe("OpenCodeEmitter", () => {
  it("emits a command at .opencode/commands with description frontmatter", () => {
    const file = new OpenCodeEmitter().emit([spec], ctx(false))[0]!;
    expect(file.path).toBe(".opencode/commands/amby.specify.md");
    expect(file.contents).toContain('description: "Turn a feature idea into a spec."');
    expect(file.contents).toContain("$ARGUMENTS"); // kept verbatim
  });
});

describe("CursorEmitter", () => {
  it("emits a plain command (no frontmatter block)", () => {
    const files = new CursorEmitter().emit([spec], ctx(false));
    const cmd = files.find((f) => f.path.startsWith(".cursor/commands"))!;
    expect(cmd.path).toBe(".cursor/commands/amby.specify.md");
    expect(cmd.contents.startsWith("---")).toBe(false);
    expect(cmd.contents).toContain("GENERATED by AmbyKit");
  });

  it("emits an always-applied .mdc rule when rules are managed", () => {
    const rule = new CursorEmitter().emit([spec], ctx(true)).find((f) => f.path.endsWith(".mdc"))!;
    expect(rule.path).toBe(".cursor/rules/ambykit.mdc");
    expect(rule.contents).toContain("alwaysApply: true");
  });
});

describe("CursorCliEmitter (surface: none)", () => {
  it("emits no command files, only the reused rule", () => {
    const files = new CursorCliEmitter().emit([spec], ctx(true));
    expect(files.every((f) => !f.path.includes("/commands/"))).toBe(true);
    expect(files.find((f) => f.path.endsWith(".mdc"))).toBeDefined();
  });
});

describe("AntigravityEmitter (surface: workflows)", () => {
  it("emits a workflow at .agents/workflows with description-only frontmatter", () => {
    const file = new AntigravityEmitter().emit([spec], ctx(false))[0]!;
    expect(file.path).toBe(".agents/workflows/amby.specify.md");
    expect(file.contents).toContain('description: "Turn a feature idea into a spec."');
    expect(file.contents).not.toContain("agent:");
  });
});

describe("AntigravityCliEmitter", () => {
  it("reuses the IDE emitter's workflow output", () => {
    const ide = new AntigravityEmitter().emit([spec], ctx(false))[0]!;
    const cli = new AntigravityCliEmitter().emit([spec], ctx(false))[0]!;
    expect(cli.path).toBe(ide.path);
    expect(cli.contents).toBe(ide.contents);
  });
});
