import { join } from "node:path";
import type {
  AbstractTool,
  CommandSpec,
  CommandSurface,
  EmittedFile,
  RulesContext,
} from "../core/types.js";

/**
 * Abstract base for all tool emitters. Holds the shared orchestration (the `emit` template method)
 * and rendering helpers; subclasses override only what differs for their tool. Adding a tool should
 * be a thin subclass — never a re-implementation of `emit`.
 */
export abstract class BaseEmitter {
  /** Stable id used in config and the registry, e.g. "claude". */
  abstract readonly toolId: string;
  /** Human-readable name for CLI output. */
  abstract readonly displayName: string;
  /** How this tool materializes phase prompts. */
  abstract readonly commandSurface: CommandSurface;
  /** Directory (relative to project root) that holds command/skill/workflow files. */
  abstract readonly commandDir: string;
  /** Map from abstract capability to this tool's concrete tool name. */
  protected abstract readonly toolNameMap: Record<AbstractTool, string>;

  /** Template method: orchestrates a full emit. Subclasses do not override this. */
  emit(specs: CommandSpec[], ctx: RulesContext): EmittedFile[] {
    const files: EmittedFile[] = [];
    if (this.commandSurface !== "none") {
      for (const spec of specs) files.push(this.commandFile(spec));
    }
    if (ctx.manageRules) files.push(...this.rulesFiles(ctx));
    return files;
  }

  /** Tool-specific extra rules files (e.g. Claude's CLAUDE.md bridge). Default: none. */
  protected rulesFiles(_ctx: RulesContext): EmittedFile[] {
    return [];
  }

  // --- command file assembly (shared) ---

  /** Full project-relative path of a spec's command file. */
  protected commandFilePath(spec: CommandSpec): string {
    return join(this.commandDir, this.commandFileName(spec));
  }

  /** File name for a spec's command. Default `<name>.md` (e.g. amby.specify.md). */
  protected commandFileName(spec: CommandSpec): string {
    return `${spec.name}.md`;
  }

  /** Native frontmatter as ordered [key, serializedValue] pairs. */
  protected abstract commandFrontmatter(spec: CommandSpec): Array<[string, string]>;

  protected commandFile(spec: CommandSpec): EmittedFile {
    const front = this.renderFrontmatter(this.commandFrontmatter(spec));
    const notice = this.generatedNotice(spec);
    const contents = `${front}\n${notice}\n\n${this.transformBody(spec)}\n`;
    return { path: this.commandFilePath(spec), contents, scope: "project" };
  }

  /**
   * Transform the neutral prompt body for this tool. Default: verbatim. Tools with a different
   * argument-placeholder convention override this (e.g. Copilot swaps `$ARGUMENTS` for `${input:…}`).
   */
  protected transformBody(spec: CommandSpec): string {
    return spec.body;
  }

  protected generatedNotice(spec: CommandSpec): string {
    return `<!-- GENERATED by AmbyKit from src/prompts/${spec.id}.md — do not edit by hand; run \`ambykit sync\`. -->`;
  }

  // --- serialization helpers (shared) ---

  protected renderFrontmatter(pairs: Array<[string, string]>): string {
    const body = pairs.map(([k, v]) => `${k}: ${v}`).join("\n");
    return `---\n${body}\n---`;
  }

  /** Double-quote and escape a scalar so it is always valid YAML. */
  protected yamlQuote(value: string): string {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }

  /** Map abstract tool capabilities to this tool's concrete names, in a comma list. */
  protected mappedTools(spec: CommandSpec): string {
    return spec.allowedTools.map((t) => this.toolNameMap[t]).join(", ");
  }
}
