import { join } from "node:path/posix";
import { roleForSpec } from "../core/roles.js";
import type {
  Role,
  AbstractTool,
  CommandSpec,
  CommandSurface,
  EmittedFile,
  RulesContext,
} from "../core/types.js";

/**
 * Abstract base for all tool emitters. Holds the shared orchestration (the `emit` template method)
 * and rendering helpers; subclasses override only what differs for their tool. Adding a tool should
 * be a thin subclass — never a re-implementation of `emit`.
 */
export abstract class BaseEmitter {
  /** Stable id used in config and the registry, e.g. "claude". */
  abstract readonly toolId: string;
  /** Human-readable name for CLI output. */
  abstract readonly displayName: string;
  /** How this tool materializes phase prompts. */
  abstract readonly commandSurface: CommandSurface;
  /** Directory (relative to project root) that holds command/skill/workflow files. */
  abstract readonly commandDir: string;
  /** Map from abstract capability to this tool's concrete tool name. Override when emitting tools. */
  protected readonly toolNameMap: Record<AbstractTool, string> = {
    read: "read",
    write: "write",
    edit: "edit",
    bash: "bash",
  };

  /** Template method: orchestrates a full emit. Subclasses do not override this. */
  emit(specs: CommandSpec[], ctx: RulesContext): EmittedFile[] {
    const files: EmittedFile[] = [];
    if (this.commandSurface !== "none") {
      for (const spec of specs) files.push(this.commandFile(spec, ctx));
    }
    if (ctx.manageRules) files.push(...this.rulesFiles(ctx));
    if (ctx.roles && ctx.roles.length > 0) files.push(...this.roleFiles(ctx.roles, ctx));
    return files;
  }

  /**
   * Native persona/sub-agent files, one per role (feature 013, FR-009). Default: none — only
   * targets whose agent-file format is verified in `docs/tool-compatibility.md` override this.
   */
  protected roleFiles(_roles: Role[], _ctx: RulesContext): EmittedFile[] {
    return [];
  }

  /** Persona file name stem shared by every native format: `amby-<role id>`. */
  protected personaName(role: Role): string {
    return `amby-${role.id}`;
  }

  /** Persona system prompt: the role body plus a pointer to the shared workflow rules. */
  protected personaBody(role: Role): string {
    return `<!-- GENERATED by AmbyKit from .amby/roles/${role.id}.md — do not edit by hand; run \`ambykit sync\`. -->\n\n` +
      `You are the **${role.name}** on this project.\n\n${role.body}\n\n` +
      "Follow the AmbyKit workflow and rules in `AGENTS.md`; artifacts live under `specs/`.";
  }

  protected personaDescription(role: Role): string {
    return `${role.name} — AmbyKit role for ${role.phases.length ? role.phases.join("/") : "reviews"}; use for that perspective.`;
  }

  /** Tool-specific extra rules files (e.g. Claude's CLAUDE.md bridge). Default: none. */
  protected rulesFiles(_ctx: RulesContext): EmittedFile[] {
    return [];
  }

  // --- command file assembly (shared) ---

  /** Full project-relative path of a spec's command file. */
  protected commandFilePath(spec: CommandSpec): string {
    return join(this.commandDir, this.commandFileName(spec));
  }

  /** File name for a spec's command. Default `<name>.md` (e.g. amby.specify.md). */
  protected commandFileName(spec: CommandSpec): string {
    return `${spec.name}.md`;
  }

  /** Native frontmatter as ordered [key, serializedValue] pairs. */
  protected abstract commandFrontmatter(spec: CommandSpec): Array<[string, string]>;

  protected commandFile(spec: CommandSpec, ctx?: RulesContext): EmittedFile {
    const pairs = this.commandFrontmatter(spec);
    const notice = this.generatedNotice(spec);
    const roleLine = this.roleLine(spec, ctx);
    // The role line is prepended *before* transformBody so tool-specific placeholder rewrites
    // (e.g. Copilot's `$ARGUMENTS`) apply to its `--as` clause too.
    const body = this.transformBody(roleLine ? { ...spec, body: `${roleLine}\n\n${spec.body}` } : spec);
    // Tools with no command frontmatter (e.g. Cursor plain commands) get no `---` block.
    const head = pairs.length > 0 ? `${this.renderFrontmatter(pairs)}\n` : "";
    const contents = `${head}${notice}\n\n${body}\n`;
    return { path: this.commandFilePath(spec), contents, scope: "project" };
  }

  /**
   * Transform the neutral prompt body for this tool. Default: verbatim. Tools with a different
   * argument-placeholder convention override this (e.g. Copilot swaps `$ARGUMENTS` for `${input:…}`).
   */
  protected transformBody(spec: CommandSpec): string {
    return spec.body;
  }

  /**
   * One sentence binding the phase to its role (feature 013, FR-003/FR-005). Emitted only when the
   * project has roles installed and the spec names one; otherwise nothing, so projects without
   * `.amby/roles/` get byte-identical output (FR-004). The role is referenced by path, never
   * inlined (Principle 3).
   */
  protected roleLine(spec: CommandSpec, ctx?: RulesContext): string | null {
    const role = roleForSpec(ctx?.roles ?? [], spec.role);
    if (!role) return null;
    return (
      `Act as the **${role.name}** in \`@.amby/roles/${role.id}.md\` and say so in your first line. ` +
      "If `$ARGUMENTS` contains `--as <id>`, use `@.amby/roles/<id>.md` instead; if that file is " +
      "missing, stop and list the files in `.amby/roles/`."
    );
  }

  protected generatedNotice(spec: CommandSpec): string {
    return `<!-- GENERATED by AmbyKit from src/prompts/${spec.id}.md — do not edit by hand; run \`ambykit sync\`. -->`;
  }

  // --- serialization helpers (shared) ---

  protected renderFrontmatter(pairs: Array<[string, string]>): string {
    const body = pairs.map(([k, v]) => `${k}: ${v}`).join("\n");
    return `---\n${body}\n---`;
  }

  /** Double-quote and escape a scalar so it is always valid YAML. */
  protected yamlQuote(value: string): string {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }

  /** Map abstract tool capabilities to this tool's concrete names, in a comma list. */
  protected mappedTools(spec: CommandSpec): string {
    return spec.allowedTools.map((t) => this.toolNameMap[t]).join(", ");
  }
}
